export type CategoryId =
  | 'spiritual'
  | 'work'
  | 'health'
  | 'family'
  | 'home'
  | 'personal'
  | 'free'

export interface Category {
  id: CategoryId
  label: string
  color: string
}

export interface FlexOption {
  id: string
  label: string
}

export interface Activity {
  id: string
  title: string
  /** 24h "HH:MM" */
  startTime: string
  durationMin: number
  category?: CategoryId
  notes?: string
  isFlexible?: boolean
  flexOptions?: FlexOption[]
  /** Marks this block as a focus session: gains a docket and Productivity/Discipline scores. */
  isFocusSession?: boolean
}

export interface ActivityLog {
  id: string
  activityId: string
  activityTitle: string
  date: string // YYYY-MM-DD
  completedAsPlanned: boolean
  intendedMinutesSpent?: number
  actualActivityTitle?: string
  actualMinutesSpent?: number
  rating?: number // 0-10, non-session blocks
  notes?: string
  createdAt: string // ISO
  /** True only for the default log auto-created by Mark Complete; absent once manually edited. */
  autoGenerated?: boolean
  /** 1-10, focus-session blocks only. */
  productivityScore?: number
  /** 1-10, focus-session blocks only. */
  disciplineScore?: number
}

export type DocketTaskStatus = 'planned' | 'done' | 'skipped'

export interface DocketTask {
  id: string
  title: string
  plannedMinutes: number
  actualMinutes?: number
  status: DocketTaskStatus
}

export interface SessionTimerState {
  activityId: string
  taskId: string
  startedAt: string // ISO — when this task's timer began (used to compute actualMinutes)
  targetEndAt: string // ISO — wall-clock end time; countdown is always derived from this, not decremented
  /** Present only while paused; holds the frozen remaining ms. */
  pausedRemainingMs?: number
}

export interface StartOverride {
  activityId: string
  actualStartMinutes: number
}

export interface PlanProfile {
  id: string
  name: string
  activities: Activity[]
}

export type Weekday = 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun'

export type DayMapping = Record<Weekday, string>

export interface DayState {
  date: string // YYYY-MM-DD
  completedIds: string[]
  override?: StartOverride
  logs: ActivityLog[]
  /** Per-date profile choice, overriding the day-of-week mapping for this date only. */
  profileOverride?: string
  /**
   * The activities actually used on this date, locked in once the date is no longer
   * "today" so later profile/mapping edits can't retroactively change history.
   */
  activitiesSnapshot?: Activity[]
  /** Focus-session dockets for this date, keyed by activity id. */
  dockets?: Record<string, DocketTask[]>
  /** At most one focus-session task timer running/paused per day. */
  activeSessionTimer?: SessionTimerState
}

export type ThemePreference = 'system' | 'light' | 'dark'

export interface AppDataExport {
  version: 1
  exportedAt: string // ISO
  profiles: PlanProfile[]
  defaultProfileId: string
  dayMapping: DayMapping
  dayStates: DayState[]
}
