export type CategoryId =
  | 'spiritual'
  | 'work'
  | 'health'
  | 'family'
  | 'home'
  | 'personal'
  | 'free'

export interface Category {
  id: CategoryId
  label: string
  color: string
}

export interface FlexOption {
  id: string
  label: string
}

export interface Activity {
  id: string
  title: string
  /** 24h "HH:MM" */
  startTime: string
  durationMin: number
  category?: CategoryId
  notes?: string
  isFlexible?: boolean
  flexOptions?: FlexOption[]
  /** Marks this block as a focus session: gains a docket and Productivity/Discipline scores. */
  isFocusSession?: boolean
  /** Marks this block as an AWAKEN block: a sequence of timed morning practices. */
  isAwaken?: boolean
  /** Practice templates for an AWAKEN block, in order. Falls back to the default six when absent. */
  awakenPractices?: AwakenPracticeTemplate[]
}

export interface AwakenPracticeTemplate {
  id: string
  title: string
  enabled: boolean
}

export interface ActivityLog {
  id: string
  activityId: string
  activityTitle: string
  date: string // YYYY-MM-DD
  completedAsPlanned: boolean
  intendedMinutesSpent?: number
  actualActivityTitle?: string
  actualMinutesSpent?: number
  rating?: number // 0-10, non-session blocks
  notes?: string
  createdAt: string // ISO
  /** True only for the default log auto-created by Mark Complete; absent once manually edited. */
  autoGenerated?: boolean
  /** 1-10, focus-session blocks only. */
  productivityScore?: number
  /** 1-10, focus-session blocks only. */
  disciplineScore?: number
}

export type DocketTaskStatus = 'planned' | 'done' | 'skipped'

export interface DocketTask {
  id: string
  title: string
  plannedMinutes: number
  actualMinutes?: number
  status: DocketTaskStatus
  /**
   * Milliseconds already spent on this task from an earlier period that
   * ended by switching away (not by completing it) — banked so resuming it
   * later continues from where it left off instead of restarting at its
   * full planned duration. Undefined for a task that's never been active,
   * or once it's marked done/skipped (actualMinutes is the final record).
   */
  elapsedMs?: number
}

export interface SessionTimerState {
  activityId: string
  taskId: string
  startedAt: string // ISO — when this task's timer began (used to compute actualMinutes)
  targetEndAt: string // ISO — wall-clock end time; countdown is always derived from this, not decremented
  /** Present only while paused; holds the frozen remaining ms. */
  pausedRemainingMs?: number
}

export interface StartOverride {
  activityId: string
  actualStartMinutes: number
}

export interface PlanProfile {
  id: string
  name: string
  activities: Activity[]
}

export type Weekday = 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun'

export type DayMapping = Record<Weekday, string>

export interface DayState {
  date: string // YYYY-MM-DD
  completedIds: string[]
  override?: StartOverride
  logs: ActivityLog[]
  /** Per-date profile choice, overriding the day-of-week mapping for this date only. */
  profileOverride?: string
  /**
   * The activities actually used on this date, locked in once the date is no longer
   * "today" so later profile/mapping edits can't retroactively change history.
   */
  activitiesSnapshot?: Activity[]
  /** Focus-session dockets for this date, keyed by activity id. */
  dockets?: Record<string, DocketTask[]>
  /** At most one focus-session task timer running/paused per day. */
  activeSessionTimer?: SessionTimerState
  /**
   * Per-date override of a block's `isFocusSession` flag, keyed by activity
   * id — set from the Today screen without touching the activity's own
   * definition in its profile template. Wins over the template value for
   * this date only; absent entries fall back to the template.
   */
  focusSessionOverrides?: Record<string, boolean>
}

/**
 * A standalone to-do, independent of any date or Activity block — unlike
 * DocketTask above (day-scoped, nested under a specific focus-session
 * activity), a PlanTask lives in its own top-level list and persists
 * indefinitely. Phase 1 (this type) has no Focus Session wiring at all;
 * `timeSpentMinutes` is edited by hand only. When Phase 2 adds real
 * elapsed-time tracking from Focus Sessions, that manual edit path stays —
 * it's the correction mechanism for a mis-timed session, not a stopgap to
 * remove once auto-tracking exists.
 */
export interface PlanTask {
  id: string
  title: string
  /** The original estimate — never mutated automatically, including once time is logged against it. */
  estimatedMinutes: number
  /** Manually edited only (Phase 1); the intended correction path even after Phase 2 adds automatic tracking. */
  timeSpentMinutes: number
  completed: boolean
  /** Flat, full-list sort position — renumbered on every drag-drop, same convention as Activity ordering. */
  order: number
  createdAt: string // ISO
  updatedAt: string // ISO
}

export type ThemePreference = 'system' | 'light' | 'dark'

export interface AppDataExport {
  version: 1
  exportedAt: string // ISO
  profiles: PlanProfile[]
  defaultProfileId: string
  dayMapping: DayMapping
  dayStates: DayState[]
}
