export type CategoryId =
  | 'spiritual'
  | 'work'
  | 'health'
  | 'family'
  | 'home'
  | 'personal'
  | 'free'

export interface Category {
  id: CategoryId
  label: string
  color: string
}

export interface FlexOption {
  id: string
  label: string
}

export interface Activity {
  id: string
  title: string
  /** 24h "HH:MM" */
  startTime: string
  durationMin: number
  category?: CategoryId
  notes?: string
  isFlexible?: boolean
  flexOptions?: FlexOption[]
}

export interface ActivityLog {
  id: string
  activityId: string
  activityTitle: string
  date: string // YYYY-MM-DD
  completedAsPlanned: boolean
  intendedMinutesSpent?: number
  actualActivityTitle?: string
  actualMinutesSpent?: number
  rating?: number // 0-10
  notes?: string
  createdAt: string // ISO
  /** True only for the default log auto-created by Mark Complete; absent once manually edited. */
  autoGenerated?: boolean
}

export interface StartOverride {
  activityId: string
  actualStartMinutes: number
}

export interface PlanProfile {
  id: string
  name: string
  activities: Activity[]
}

export type Weekday = 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun'

export type DayMapping = Record<Weekday, string>

export interface DayState {
  date: string // YYYY-MM-DD
  completedIds: string[]
  override?: StartOverride
  logs: ActivityLog[]
  /** Per-date profile choice, overriding the day-of-week mapping for this date only. */
  profileOverride?: string
  /**
   * The activities actually used on this date, locked in once the date is no longer
   * "today" so later profile/mapping edits can't retroactively change history.
   */
  activitiesSnapshot?: Activity[]
}

export type ThemePreference = 'system' | 'light' | 'dark'
